"""Architecture diagrams for the dashboard's "Sơ đồ" tab.

The HTML files in ``app/diagrams/`` are generated by archify from the JSON sources in
``docs/architecture/`` (regenerate with ``archify deliver``; never hand-edit the HTML). Each one
is a self-contained viewer with inline ``<script>``/``<style>``, which the app-wide CSP
(``script-src 'self'``, ``X-Frame-Options: DENY``) rightly refuses. This route relaxes the policy
for these whitelisted files only, and pays for it with a CSP ``sandbox``: the page runs in an
opaque origin (no cookies, no same-origin API access, no ``X-API-Key`` from localStorage) and
``connect-src 'none'`` stops it reaching anything at all. The dashboard itself keeps the strict
policy; the security middleware only fills in headers a response did not set.
"""

from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

DIAGRAM_DIR = Path(__file__).parent / "diagrams"

# name -> (tab label, the question the diagram answers). Order is the tab's reading order.
DIAGRAMS: dict[str, tuple[str, str]] = {
    "overview": ("Kiến trúc tổng thể", "App gồm những khối nào và nối với nhau ra sao?"),
    "scheduler-cycle": ("Vòng Scheduler", "Mỗi 15 phút và mỗi 90 giây app làm gì, theo thứ tự nào?"),
    "scanner-pipeline": ("Scanner chọn coin", "Vì sao một coin được mở phiên hoặc bị bỏ qua?"),
    "kss-session": ("Vòng đời phiên KSS", "Một phiên đi từ lúc mở tới lúc chốt lời hoặc dừng thế nào?"),
    "order-path": ("Đường đi của lệnh", "Một lệnh được xếp, duyệt và khớp trong paper ra sao?"),
}

_CSP = (
    "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; "
    "img-src data: blob:; font-src data:; media-src blob:; connect-src 'none'; "
    "base-uri 'none'; form-action 'none'; frame-ancestors 'self'; "
    "sandbox allow-scripts allow-downloads"
)

router = APIRouter(tags=["ui"])


@router.get("/diagrams/{name}", include_in_schema=False)
def diagram(name: str) -> FileResponse:
    # Whitelist lookup, never a path join on user input: unknown names (and any traversal
    # attempt) are simply not keys.
    if name not in DIAGRAMS:
        raise HTTPException(status_code=404, detail="unknown diagram")
    return FileResponse(
        DIAGRAM_DIR / f"{name}.html",
        media_type="text/html; charset=utf-8",
        headers={"Content-Security-Policy": _CSP, "X-Frame-Options": "SAMEORIGIN"},
    )
